
/* dm 
    创建 tablespace user(n9e_v6) 请根据实际情况处理
*/

conn sysdba/SYSDBACLOUD
create tablespace n9e_v6 datafile '/opt/dmdbms/data/n9e/n9e_v6.dbf' size 128 autoextend on next 100 maxsize 102400;
create user n9e_v6 identified by "Devops123@n9e" limit password_life_time unlimited default tablespace n9e_v6;
conn sysdba/SYSDBACLOUD
grant dba to n9e_v6;
conn n9e_v6/Devops123@n9e

drop table if exists "N9E_V6"."USERS" cascade;
CREATE TABLE "N9E_V6"."USERS"
(
"ID" BIGINT IDENTITY(2, 1) NOT NULL,
"USERNAME" VARCHAR(64) NOT NULL,
"NICKNAME" VARCHAR(64) NOT NULL,
"PASSWORD" VARCHAR(128) DEFAULT '' NOT NULL,
"PHONE" VARCHAR(16) DEFAULT '' NOT NULL,
"EMAIL" VARCHAR(64) DEFAULT '' NOT NULL,
"PORTRAIT" VARCHAR(255) DEFAULT '' NOT NULL,
"ROLES" VARCHAR(255) NOT NULL,
"CONTACTS" VARCHAR(1024),
"MAINTAINER" TINYINT DEFAULT 0 NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "USERNAME" UNIQUE("USERNAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."USERS"."USERNAME" IS 'login name, cannot rename';
COMMENT ON COLUMN "N9E_V6"."USERS"."NICKNAME" IS 'display name, chinese name';
COMMENT ON COLUMN "N9E_V6"."USERS"."PORTRAIT" IS 'portrait image url';
COMMENT ON COLUMN "N9E_V6"."USERS"."ROLES" IS 'Admin | Standard | Guest, split by space';
COMMENT ON COLUMN "N9E_V6"."USERS"."CONTACTS" IS 'json e.g. {wecom:xx, dingtalk_robot_token:yy}';

SET IDENTITY_INSERT "N9E_V6"."USERS" ON;
insert into "N9E_V6"."USERS"(id, username, nickname, password, roles, create_at, create_by, update_at, update_by) values(1, 'root', '超管', 'root.2020', 'Admin', unix_timestamp(now()), 'system', unix_timestamp(now()), 'system');

drop table if exists "N9E_V6"."USER_GROUP" cascade;
CREATE TABLE "N9E_V6"."USER_GROUP"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"NAME" VARCHAR(128) DEFAULT '' NOT NULL,
"NOTE" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "CREATE_BY" ON "N9E_V6"."USER_GROUP"("CREATE_BY" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "INDEX100020740746700" ON "N9E_V6"."USER_GROUP"("UPDATE_AT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
SET IDENTITY_INSERT "N9E_V6"."USER_GROUP" ON;
insert into "N9E_V6"."USER_GROUP"(id, name, create_at, create_by, update_at, update_by) values(1, 'demo-root-group', unix_timestamp(now()), 'root', unix_timestamp(now()), 'root');

drop table if exists "N9E_V6"."USER_GROUP_MEMBER" cascade;
CREATE TABLE "N9E_V6"."USER_GROUP_MEMBER"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"GROUP_ID" DECIMAL(20,0) NOT NULL,
"USER_ID" DECIMAL(20,0) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CHECK("GROUP_ID" >= 0)
,CHECK("USER_ID" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "INDEX100023354058300" ON "N9E_V6"."USER_GROUP_MEMBER"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "USER_ID" ON "N9E_V6"."USER_GROUP_MEMBER"("USER_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
SET IDENTITY_INSERT "N9E_V6"."USER_GROUP_MEMBER" ON;
insert into "N9E_V6"."USER_GROUP_MEMBER"(id, group_id, user_id) values(1,1, 1);

drop table if exists "N9E_V6"."CONFIGS" cascade;
CREATE TABLE "N9E_V6"."CONFIGS"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"CKEY" VARCHAR(191) NOT NULL,
"CVAL" TEXT,
"NOTE" VARCHAR(1024) DEFAULT '',
"EXTERNAL" BIGINT DEFAULT 0,
"ENCRYPTED" BIGINT DEFAULT 0,
"CREATE_AT" BIGINT DEFAULT 0,
"CREATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_AT" BIGINT DEFAULT 0,
"UPDATE_BY" VARCHAR(64) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."CONFIGS"."CVAL" IS 'config value';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."NOTE" IS 'note';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."EXTERNAL" IS '0:built-in 1:external';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."ENCRYPTED" IS '0:plaintext 1:ciphertext';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."CREATE_AT" IS 'create_at';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."CREATE_BY" IS 'cerate_by';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."UPDATE_AT" IS 'update_at';
COMMENT ON COLUMN "N9E_V6"."CONFIGS"."UPDATE_BY" IS 'update_by';

drop table if exists "N9E_V6"."ROLE" cascade;
CREATE TABLE "N9E_V6"."ROLE"
(
"ID" BIGINT IDENTITY(3, 1) NOT NULL,
"NAME" VARCHAR(191) DEFAULT '' NOT NULL,
"NOTE" VARCHAR(255) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("NAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

SET IDENTITY_INSERT "N9E_V6"."ROLE" ON;
insert into "N9E_V6"."ROLE"(id, name, note) values(1, 'Admin', 'Administrator role');
insert into "N9E_V6"."ROLE"(id, name, note) values(2, 'Standard', 'Ordinary user role');
insert into "N9E_V6"."ROLE"(id, name, note) values(3, 'Guest', 'Readonly user role');

drop table if exists "N9E_V6"."ROLE_OPERATION" cascade;
CREATE TABLE "N9E_V6"."ROLE_OPERATION"
(
"ID" BIGINT IDENTITY(67, 1) NOT NULL,
"ROLE_NAME" VARCHAR(128) NOT NULL,
"OPERATION" VARCHAR(191) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "OPERATION" ON "N9E_V6"."ROLE_OPERATION"("OPERATION" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ROLE_NAME" ON "N9E_V6"."ROLE_OPERATION"("ROLE_NAME" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
SET IDENTITY_INSERT "N9E_V6"."ROLE_OPERATION" ON;
-- Admin is special, who has no concrete operation but can do anything.
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (1, 'Guest', '/metric/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (2, 'Guest', '/object/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (3, 'Guest', '/log/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (4, 'Guest', '/trace/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (5, 'Guest', '/help/version');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (6, 'Guest', '/help/contact');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (7, 'Admin', '/help/source');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (8, 'Admin', '/help/sso');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (9, 'Admin', '/help/notification-tpls');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (10, 'Admin', '/help/notification-settings');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (11, 'Admin', '/permissions');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (12, 'Standard', '/metric/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (13, 'Standard', '/object/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (14, 'Standard', '/log/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (15, 'Standard', '/trace/explorer');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (16, 'Standard', '/help/version');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (17, 'Standard', '/help/contact');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (18, 'Standard', '/help/servers');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (19, 'Standard', '/help/migrate');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (20, 'Standard', '/alert-rules-built-in');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (21, 'Standard', '/dashboards-built-in');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (22, 'Standard', '/trace/dependencies');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (23, 'Standard', '/users');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (24, 'Standard', '/user-groups');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (25, 'Standard', '/user-groups/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (26, 'Standard', '/user-groups/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (27, 'Standard', '/user-groups/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (28, 'Standard', '/busi-groups');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (29, 'Standard', '/busi-groups/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (30, 'Standard', '/busi-groups/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (31, 'Standard', '/busi-groups/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (32, 'Standard', '/targets');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (33, 'Standard', '/targets/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (34, 'Standard', '/targets/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (35, 'Standard', '/targets/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (36, 'Standard', '/dashboards');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (37, 'Standard', '/dashboards/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (38, 'Standard', '/dashboards/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (39, 'Standard', '/dashboards/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (40, 'Standard', '/alert-rules');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (41, 'Standard', '/alert-rules/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (42, 'Standard', '/alert-rules/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (43, 'Standard', '/alert-rules/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (44, 'Standard', '/alert-mutes');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (45, 'Standard', '/alert-mutes/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (46, 'Standard', '/alert-mutes/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (47, 'Standard', '/alert-subscribes');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (48, 'Standard', '/alert-subscribes/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (49, 'Standard', '/alert-subscribes/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (50, 'Standard', '/alert-subscribes/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (51, 'Standard', '/alert-cur-events');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (52, 'Standard', '/alert-cur-events/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (53, 'Standard', '/alert-his-events');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (54, 'Standard', '/job-tpls');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (55, 'Standard', '/job-tpls/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (56, 'Standard', '/job-tpls/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (57, 'Standard', '/job-tpls/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (58, 'Standard', '/job-tasks');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (59, 'Standard', '/job-tasks/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (60, 'Standard', '/job-tasks/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (61, 'Standard', '/recording-rules');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (62, 'Standard', '/recording-rules/add');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (63, 'Standard', '/recording-rules/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (64, 'Standard', '/recording-rules/del');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (65, 'Standard', '/alert-mutes/put');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (66, 'Standard', '/log/index-patterns');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (67, 'Standard', '/help/variable-configs');
INSERT INTO "N9E_V6"."ROLE_OPERATION"(id, role_name, operation) VALUES (68, 'Standard', '/ibex-settings');

-- for alert_rule | collect_rule | mute | dashboard grouping
drop table if exists "N9E_V6"."BUSI_GROUP" cascade;
CREATE TABLE "N9E_V6"."BUSI_GROUP"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"NAME" VARCHAR(191) NOT NULL,
"LABEL_ENABLE" TINYINT DEFAULT 0 NOT NULL,
"LABEL_VALUE" VARCHAR(191) DEFAULT '' NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "NAME" UNIQUE("NAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."BUSI_GROUP"."LABEL_VALUE" IS 'if label_enable: label_value can not be blank';
SET IDENTITY_INSERT "N9E_V6"."BUSI_GROUP" ON;
insert into "N9E_V6"."BUSI_GROUP"(id, name, label_enable, label_value, create_at, create_by, update_at, update_by) values(1, '默认服务组', 1, 'n9eserver', unix_timestamp(now()), 'root', unix_timestamp(now()), 'root');

drop table if exists "N9E_V6"."BUSI_GROUP_MEMBER" cascade;
CREATE TABLE "N9E_V6"."BUSI_GROUP_MEMBER"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"BUSI_GROUP_ID" BIGINT NOT NULL,
"USER_GROUP_ID" BIGINT NOT NULL,
"PERM_FLAG" CHAR(2) NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."BUSI_GROUP_MEMBER"."BUSI_GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."BUSI_GROUP_MEMBER"."USER_GROUP_ID" IS 'user group id';
COMMENT ON COLUMN "N9E_V6"."BUSI_GROUP_MEMBER"."PERM_FLAG" IS 'ro | rw';


CREATE  INDEX "BUSI_GROUP_ID" ON "N9E_V6"."BUSI_GROUP_MEMBER"("BUSI_GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "USER_GROUP_ID" ON "N9E_V6"."BUSI_GROUP_MEMBER"("USER_GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
SET IDENTITY_INSERT "N9E_V6"."BUSI_GROUP_MEMBER" ON;
insert into "N9E_V6"."BUSI_GROUP_MEMBER"(id, busi_group_id, user_group_id, perm_flag) values(1, 1, 1, 'rw');

-- for dashboard new version
drop table if exists "N9E_V6"."BOARD" cascade;
CREATE TABLE "N9E_V6"."BOARD"
(
"ID" BIGINT IDENTITY(16, 1) NOT NULL,
"GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
"NAME" VARCHAR(191) NOT NULL,
"IDENT" VARCHAR(200) DEFAULT '' NOT NULL,
"TAGS" VARCHAR(255) NOT NULL,
"IS_PUBLIC" TINYINT DEFAULT 0 NOT NULL,
"BUILT_IN" TINYINT DEFAULT 0 NOT NULL,
"HIDE" TINYINT DEFAULT 0 NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("GROUP_ID", "NAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."BOARD"."GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."BOARD"."TAGS" IS 'split by space';
COMMENT ON COLUMN "N9E_V6"."BOARD"."IS_PUBLIC" IS '0:false 1:true';
COMMENT ON COLUMN "N9E_V6"."BOARD"."BUILT_IN" IS '0:false 1:true';
COMMENT ON COLUMN "N9E_V6"."BOARD"."HIDE" IS '0:false 1:true';


CREATE  INDEX "INDEX100022854384500" ON "N9E_V6"."BOARD"("IDENT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

-- for dashboard new version
drop table if exists "N9E_V6"."BOARD_PAYLOAD" cascade;
CREATE TABLE "N9E_V6"."BOARD_PAYLOAD"
(
"ID" BIGINT NOT NULL,
"PAYLOAD" TEXT NOT NULL,
CONSTRAINT "ID" UNIQUE("ID"),
CHECK("ID" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."BOARD_PAYLOAD"."ID" IS 'dashboard id';

-- deprecated
drop table if exists "N9E_V6"."DASHBOARD" cascade;
CREATE TABLE "N9E_V6"."DASHBOARD"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
 "NAME" VARCHAR(191) NOT NULL,
 "TAGS" VARCHAR(255) NOT NULL,
 "CONFIGS" TEXT NULL,
 "CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
 "UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("GROUP_ID", "NAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

-- deprecated
-- auto create the first subclass 'Default chart group' of dashboard
drop table if exists "N9E_V6"."CHART_GROUP" cascade;
CREATE TABLE "N9E_V6"."CHART_GROUP"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"DASHBOARD_ID" BIGINT NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"WEIGHT" INT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CHECK("DASHBOARD_ID" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "DASHBOARD_ID" ON "N9E_V6"."CHART_GROUP"("DASHBOARD_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

-- deprecated
drop table if exists "N9E_V6"."CHART" cascade;
CREATE TABLE "N9E_V6"."CHART"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"GROUP_ID" DECIMAL(20,0) NOT NULL,
"CONFIGS" TEXT,
"WEIGHT" INT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CHECK("GROUP_ID" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."CHART"."GROUP_ID" IS 'chart group id';


CREATE  INDEX "INDEX100022888317700" ON "N9E_V6"."CHART"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."CHART_SHARE" cascade;
CREATE TABLE "N9E_V6"."CHART_SHARE"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"CLUSTER_NAME" VARCHAR(128) NOT NULL,
"DATASOURCE_ID" BIGINT DEFAULT 0 NOT NULL,
"CONFIGS" TEXT,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."CHART_SHARE"."DATASOURCE_ID" IS 'datasource id';

CREATE  INDEX "INDEX100020581023600" ON "N9E_V6"."CHART_SHARE"("CREATE_AT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."ALERT_RULE" cascade;
CREATE TABLE "N9E_V6"."ALERT_RULE"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
"CATE" VARCHAR(128) NOT NULL,
"DATASOURCE_IDS" VARCHAR(255) DEFAULT '' NOT NULL,
"CLUSTER_NAME" VARCHAR(128) NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"NOTE" VARCHAR(1024) DEFAULT '' NOT NULL,
"PROD" VARCHAR(255) DEFAULT '' NOT NULL,
"ALGORITHM" VARCHAR(255) DEFAULT '' NOT NULL,
"ALGO_PARAMS" VARCHAR(255),
"DELAY" INT DEFAULT 0 NOT NULL,
"SEVERITY" TINYINT NOT NULL,
"DISABLED" TINYINT NOT NULL,
"PROM_FOR_DURATION" INT NOT NULL,
"RULE_CONFIG" TEXT NOT NULL,
"PROM_QL" TEXT NOT NULL,
"PROM_EVAL_INTERVAL" INT NOT NULL,
"ENABLE_STIME" VARCHAR(255) DEFAULT '00:00' NOT NULL,
"ENABLE_ETIME" VARCHAR(255) DEFAULT '23:59' NOT NULL,
"ENABLE_DAYS_OF_WEEK" VARCHAR(255) DEFAULT '' NOT NULL,
"ENABLE_IN_BG" TINYINT DEFAULT 0 NOT NULL,
"NOTIFY_RECOVERED" TINYINT NOT NULL,
"NOTIFY_CHANNELS" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTIFY_GROUPS" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTIFY_REPEAT_STEP" INT DEFAULT 0 NOT NULL,
"NOTIFY_MAX_NUMBER" INT DEFAULT 0 NOT NULL,
"RECOVER_DURATION" INT DEFAULT 0 NOT NULL,
"CALLBACKS" VARCHAR(255) DEFAULT '' NOT NULL,
"RUNBOOK_URL" VARCHAR(255),
"APPEND_TAGS" VARCHAR(255) DEFAULT '' NOT NULL,
"ANNOTATIONS" TEXT NOT NULL,
"EXTRA_CONFIG" TEXT NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."DATASOURCE_IDS" IS 'datasource ids';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."SEVERITY" IS '1:Emergency 2:Warning 3:Notice';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."DISABLED" IS '0:enabled 1:disabled';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."PROM_FOR_DURATION" IS 'prometheus for, unit:s';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."RULE_CONFIG" IS 'rule_config';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."PROM_QL" IS 'promql';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."PROM_EVAL_INTERVAL" IS 'evaluate interval';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."ENABLE_DAYS_OF_WEEK" IS 'split by space: 0 1 2 3 4 5 6';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."ENABLE_IN_BG" IS '1: only this bg 0: global';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."NOTIFY_RECOVERED" IS 'whether notify when recovery';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."NOTIFY_CHANNELS" IS 'split by space: sms voice email dingtalk wecom';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."NOTIFY_GROUPS" IS 'split by space: 233 43';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."NOTIFY_REPEAT_STEP" IS 'unit: min';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."RECOVER_DURATION" IS 'unit: s';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."CALLBACKS" IS 'split by space: http://a.com/api/x http://a.com/api/y';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."APPEND_TAGS" IS 'split by space: service=n9e mod=api';
COMMENT ON COLUMN "N9E_V6"."ALERT_RULE"."ANNOTATIONS" IS 'annotations';


CREATE  INDEX "UPDATE_AT" ON "N9E_V6"."ALERT_RULE"("UPDATE_AT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "INDEX100020322900900" ON "N9E_V6"."ALERT_RULE"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."ALERT_MUTE" cascade;
CREATE TABLE "N9E_V6"."ALERT_MUTE"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
"PROD" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTE" VARCHAR(1024) DEFAULT '' NOT NULL,
"CATE" VARCHAR(128) NOT NULL,
"CLUSTER_NAME" VARCHAR(128) NOT NULL,
"DATASOURCE_IDS" VARCHAR(255) DEFAULT '' NOT NULL,
"TAGS" VARCHAR(4096) DEFAULT '' NOT NULL,
"CAUSE" VARCHAR(255) DEFAULT '' NOT NULL,
"BTIME" BIGINT DEFAULT 0 NOT NULL,
"ETIME" BIGINT DEFAULT 0 NOT NULL,
"DISABLED" TINYINT DEFAULT 0 NOT NULL,
"MUTE_TIME_TYPE" TINYINT DEFAULT 0 NOT NULL,
"PERIODIC_MUTES" VARCHAR(4096) DEFAULT '' NOT NULL,
"SEVERITIES" VARCHAR(32) DEFAULT '' NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."ALERT_MUTE"."GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."ALERT_MUTE"."DATASOURCE_IDS" IS 'datasource ids';
COMMENT ON COLUMN "N9E_V6"."ALERT_MUTE"."TAGS" IS 'json,map,tagkey->regexp|value';
COMMENT ON COLUMN "N9E_V6"."ALERT_MUTE"."BTIME" IS 'begin time';
COMMENT ON COLUMN "N9E_V6"."ALERT_MUTE"."ETIME" IS 'end time';
COMMENT ON COLUMN "N9E_V6"."ALERT_MUTE"."DISABLED" IS '0:enabled 1:disabled';


CREATE  INDEX "CREATE_AT" ON "N9E_V6"."ALERT_MUTE"("CREATE_AT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "GROUP_ID" ON "N9E_V6"."ALERT_MUTE"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."ALERT_SUBSCRIBE" cascade;
CREATE TABLE "N9E_V6"."ALERT_SUBSCRIBE"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"NAME" VARCHAR(255) DEFAULT '' NOT NULL,
"DISABLED" TINYINT DEFAULT 0 NOT NULL,
"GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
"PROD" VARCHAR(255) DEFAULT '' NOT NULL,
"CATE" VARCHAR(128) NOT NULL,
"DATASOURCE_IDS" VARCHAR(255) DEFAULT '' NOT NULL,
"CLUSTER_NAME" VARCHAR(128) NOT NULL,
"RULE_ID" BIGINT DEFAULT 0 NOT NULL,
"SEVERITIES" VARCHAR(32) DEFAULT '' NOT NULL,
"TAGS" VARCHAR(4096) DEFAULT '' NOT NULL,
"REDEFINE_SEVERITY" TINYINT DEFAULT 0,
"NEW_SEVERITY" TINYINT NOT NULL,
"REDEFINE_CHANNELS" TINYINT DEFAULT 0,
"NEW_CHANNELS" VARCHAR(255) DEFAULT '' NOT NULL,
"USER_GROUP_IDS" VARCHAR(250) NOT NULL,
"WEBHOOKS" TEXT NOT NULL,
"EXTRA_CONFIG" TEXT NOT NULL,
"REDEFINE_WEBHOOKS" TINYINT DEFAULT 0,
"FOR_DURATION" BIGINT DEFAULT 0 NOT NULL,
"NOTE" VARCHAR(1024) DEFAULT '',
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"BUSI_GROUPS" VARCHAR(4096) DEFAULT '[]' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."DISABLED" IS '0:enabled 1:disabled';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."DATASOURCE_IDS" IS 'datasource ids';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."TAGS" IS 'json,map,tagkey->regexp|value';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."REDEFINE_SEVERITY" IS 'is redefine severity?';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."NEW_SEVERITY" IS '0:Emergency 1:Warning 2:Notice';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."REDEFINE_CHANNELS" IS 'is redefine channels?';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."NEW_CHANNELS" IS 'split by space: sms voice email dingtalk wecom';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."USER_GROUP_IDS" IS 'split by space 1 34 5, notify cc to user_group_ids';
COMMENT ON COLUMN "N9E_V6"."ALERT_SUBSCRIBE"."NOTE" IS 'note';

CREATE  INDEX "INDEX100020372398800" ON "N9E_V6"."ALERT_SUBSCRIBE"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "INDEX100020436016700" ON "N9E_V6"."ALERT_SUBSCRIBE"("UPDATE_AT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."TARGET" cascade;
CREATE TABLE "N9E_V6"."TARGET"
(
"ID" BIGINT IDENTITY(2, 1) NOT NULL,
"GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
"IDENT" VARCHAR(191) NOT NULL,
"NOTE" VARCHAR(255) DEFAULT '' NOT NULL,
"TAGS" VARCHAR(512) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"HOST_IP" VARCHAR(191) DEFAULT '',
"AGENT_VERSION" VARCHAR(255) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "IDENT" UNIQUE("IDENT")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."TARGET"."GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."TARGET"."IDENT" IS 'target id';
COMMENT ON COLUMN "N9E_V6"."TARGET"."NOTE" IS 'append to alert event as field';
COMMENT ON COLUMN "N9E_V6"."TARGET"."TAGS" IS 'append to series data as tags, split by space, append external space at suffix';
COMMENT ON COLUMN "N9E_V6"."TARGET"."HOST_IP" IS 'IPv4 string';
COMMENT ON COLUMN "N9E_V6"."TARGET"."AGENT_VERSION" IS 'agent version';


CREATE  INDEX "INDEX100022986596800" ON "N9E_V6"."TARGET"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "IDX_HOST_IP" ON "N9E_V6"."TARGET"("HOST_IP" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "IDX_AGENT_VERSION" ON "N9E_V6"."TARGET"("AGENT_VERSION" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;


-- case1: target_idents; case2: target_tags
-- CREATE TABLE collect_rule (
--     id bigint unsigned not null auto_increment,
--     group_id bigint not null default 0 ,
--     cluster_name varchar(128) not null,
--     target_idents varchar(512) not null default '' ,
--     target_tags varchar(512) not null default '' ,
--     name varchar(191) not null default '',
--     note varchar(255) not null default '',
--     step int not null,
--     type varchar(64) not null ,
--     data text not null,
--     append_tags varchar(255) not null default '' ,
--     create_at bigint not null default 0,
--     create_by varchar(64) not null default '',
--     update_at bigint not null default 0,
--     update_by varchar(64) not null default '',
--     PRIMARY KEY (id),
--     KEY (group_id, type, name)
-- ) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

drop table if exists "N9E_V6"."METRIC_VIEW" cascade;
CREATE TABLE "N9E_V6"."METRIC_VIEW"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "NAME" VARCHAR(191) DEFAULT '' NOT NULL,
 "CATE" TINYINT NOT NULL,
 "CONFIGS" TEXT  DEFAULT '' NOT NULL,
 "CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
 "CREATE_BY" BIGINT DEFAULT 0 NOT NULL,
 "UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "METRIC_VIEW_CREATE_BY" ON "N9E_V6"."METRIC_VIEW"("CREATE_BY" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
SET IDENTITY_INSERT "N9E_V6"."METRIC_VIEW" ON;
insert into "N9E_V6"."METRIC_VIEW"(id, name, cate, configs) values(1, 'Host View', 0, '{"filters":[{"oper":"=","label":"__name__","value":"cpu_usage_idle"}],"dynamicLabels":[],"dimensionLabels":[{"label":"ident","value":""}]}');

drop table if exists "N9E_V6"."RECORDING_RULE" cascade;
CREATE TABLE "N9E_V6"."RECORDING_RULE"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "GROUP_ID" BIGINT DEFAULT 0 NOT NULL,
 "DATASOURCE_IDS" VARCHAR(255) DEFAULT '' NOT NULL,
 "CLUSTER_NAME" VARCHAR(128) NOT NULL,
 "NAME" VARCHAR(255) NOT NULL,
 "NOTE" VARCHAR(255) NOT NULL,
 "DISABLED" TINYINT DEFAULT 0 NOT NULL,
 "PROM_QL" TEXT NOT NULL,
 "PROM_EVAL_INTERVAL" INT NOT NULL,
 "APPEND_TAGS" VARCHAR(255) DEFAULT '' NULL,
 "QUERY_CONFIGS" TEXT NOT NULL,
 "CREATE_AT" BIGINT DEFAULT 0 NULL,
 "CREATE_BY" VARCHAR(64) DEFAULT '' NULL,
 "UPDATE_AT" BIGINT DEFAULT 0 NULL,
 "UPDATE_BY" VARCHAR(64) DEFAULT '' NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "RECORDING_RULE_GROUP_ID" ON "N9E_V6"."RECORDING_RULE"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "RECORDING_RULE_UPDATE_AT" ON "N9E_V6"."RECORDING_RULE"("UPDATE_AT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;


drop table if exists "N9E_V6"."ALERT_AGGR_VIEW" cascade;
CREATE TABLE "N9E_V6"."ALERT_AGGR_VIEW"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"NAME" VARCHAR(191) DEFAULT '' NOT NULL,
"RULE" VARCHAR(2048) DEFAULT '' NOT NULL,
"CATE" TINYINT NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "ALERT_AGGR_VIEW_CREATE_BY" ON "N9E_V6"."ALERT_AGGR_VIEW"("CREATE_BY" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
SET IDENTITY_INSERT "N9E_V6"."ALERT_AGGR_VIEW" ON;
insert into "N9E_V6"."ALERT_AGGR_VIEW"(id, name, rule, cate) values(1, 'By BusiGroup, Severity', 'field:group_name::field:severity', 0);
insert into "N9E_V6"."ALERT_AGGR_VIEW"(id, name, rule, cate) values(2, 'By RuleName', 'field:rule_name', 0);

drop table if exists "N9E_V6"."ALERT_CUR_EVENT" cascade;
CREATE TABLE "N9E_V6"."ALERT_CUR_EVENT"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"CATE" VARCHAR(128) NOT NULL,
"DATASOURCE_ID" BIGINT DEFAULT 0 NOT NULL,
"CLUSTER_NAME" VARCHAR(128) NOT NULL,
"GROUP_ID" BIGINT NOT NULL,
"GROUP_NAME" VARCHAR(255) DEFAULT '' NOT NULL,
"HASH" VARCHAR(64) NOT NULL,
"RULE_ID" BIGINT NOT NULL,
"RULE_NAME" VARCHAR(255) NOT NULL,
"RULE_NOTE" VARCHAR(2048) DEFAULT 'alert rule note' NOT NULL,
"RULE_PROD" VARCHAR(255) DEFAULT '' NOT NULL,
"RULE_ALGO" VARCHAR(255) DEFAULT '' NOT NULL,
"SEVERITY" TINYINT NOT NULL,
"PROM_FOR_DURATION" INT NOT NULL,
"PROM_QL" TEXT NOT NULL,
"PROM_EVAL_INTERVAL" INT NOT NULL,
"CALLBACKS" VARCHAR(255) DEFAULT '' NOT NULL,
"RUNBOOK_URL" VARCHAR(255) DEFAULT NULL,
"NOTIFY_RECOVERED" TINYINT NOT NULL,
"NOTIFY_CHANNELS" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTIFY_GROUPS" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTIFY_REPEAT_NEXT" BIGINT DEFAULT 0 NOT NULL,
"NOTIFY_CUR_NUMBER" INT DEFAULT 0 NOT NULL,
"TARGET_IDENT" VARCHAR(191) DEFAULT '' NOT NULL,
"TARGET_NOTE" VARCHAR(191) DEFAULT '' NOT NULL,
"FIRST_TRIGGER_TIME" BIGINT DEFAULT NULL,
"TRIGGER_TIME" BIGINT NOT NULL,
"TRIGGER_VALUE" VARCHAR(255) NOT NULL,
"ANNOTATIONS" TEXT NOT NULL,
"RULE_CONFIG" TEXT NOT NULL,
"TAGS" VARCHAR(1024) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "ALERT_CUR_EVENT_HASH" ON "N9E_V6"."ALERT_CUR_EVENT"("HASH" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ALERT_CUR_EVENT_RULE_ID" ON "N9E_V6"."ALERT_CUR_EVENT"("RULE_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ALERT_CUR_EVENT_TRIGGER_TIME_GROUP_ID" ON "N9E_V6"."ALERT_CUR_EVENT"("TRIGGER_TIME" ASC,"GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ALERT_CUR_EVENT_NOTIFY_REPEAT_NEXT" ON "N9E_V6"."ALERT_CUR_EVENT"("NOTIFY_REPEAT_NEXT" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;


drop table if exists "N9E_V6"."ALERT_HIS_EVENT" cascade;
CREATE TABLE "N9E_V6"."ALERT_HIS_EVENT"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"IS_RECOVERED" TINYINT NOT NULL,
"CATE" VARCHAR(128) NOT NULL,
"DATASOURCE_ID" BIGINT DEFAULT 0 NOT NULL,
"CLUSTER_NAME" VARCHAR(128) NOT NULL,
"GROUP_ID" BIGINT NOT NULL,
"GROUP_NAME" VARCHAR(255) DEFAULT '' NOT NULL,
"HASH" VARCHAR(64) NOT NULL,
"RULE_ID" BIGINT NOT NULL,
"RULE_NAME" VARCHAR(255) NOT NULL,
"RULE_NOTE" VARCHAR(2048) DEFAULT 'alert rule note' NOT NULL,
"RULE_PROD" VARCHAR(255) DEFAULT '' NOT NULL,
"RULE_ALGO" VARCHAR(255) DEFAULT '' NOT NULL,
"SEVERITY" TINYINT NOT NULL,
"PROM_FOR_DURATION" INT NOT NULL,
"PROM_QL" TEXT NOT NULL,
"PROM_EVAL_INTERVAL" INT NOT NULL,
"CALLBACKS" VARCHAR(255) DEFAULT '' NOT NULL,
"RUNBOOK_URL" VARCHAR(255) DEFAULT NULL,
"NOTIFY_RECOVERED" TINYINT NOT NULL,
"NOTIFY_CHANNELS" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTIFY_GROUPS" VARCHAR(255) DEFAULT '' NOT NULL,
"NOTIFY_CUR_NUMBER" INT DEFAULT 0 NOT NULL,
"TARGET_IDENT" VARCHAR(191) DEFAULT '' NOT NULL,
"TARGET_NOTE" VARCHAR(191) DEFAULT '' NOT NULL,
"FIRST_TRIGGER_TIME" BIGINT DEFAULT NULL,
"TRIGGER_TIME" BIGINT NOT NULL,
"TRIGGER_VALUE" VARCHAR(255) NOT NULL,
"RECOVER_TIME" BIGINT DEFAULT 0 NOT NULL,
"LAST_EVAL_TIME" BIGINT DEFAULT 0 NOT NULL,
"TAGS" VARCHAR(1024) DEFAULT '' NOT NULL,
"ANNOTATIONS" TEXT NOT NULL,
"RULE_CONFIG" TEXT NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE  INDEX "ALERT_HIS_EVENT_HASH" ON "N9E_V6"."ALERT_HIS_EVENT"("HASH" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ALERT_HIS_EVENT_RULE_ID" ON "N9E_V6"."ALERT_HIS_EVENT"("RULE_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ALERT_HIS_EVENT_TRIGGER_TIME_GROUP_ID" ON "N9E_V6"."ALERT_HIS_EVENT"("TRIGGER_TIME" ASC,"GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "ALERT_HIS_EVENT_LAST_EVAL_TIME" ON "N9E_V6"."ALERT_HIS_EVENT"("LAST_EVAL_TIME" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."TASK_TPL" cascade;
CREATE TABLE "N9E_V6"."TASK_TPL"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"GROUP_ID" BIGINT NOT NULL,
"TITLE" VARCHAR(255) DEFAULT '' NOT NULL,
"ACCOUNT" VARCHAR(64) NOT NULL,
"BATCH" BIGINT DEFAULT 0 NOT NULL,
"TOLERANCE" BIGINT DEFAULT 0 NOT NULL,
"TIMEOUT" BIGINT DEFAULT 0 NOT NULL,
"PAUSE" VARCHAR(255) DEFAULT '' NOT NULL,
"SCRIPT" TEXT NOT NULL,
"ARGS" VARCHAR(512) DEFAULT '' NOT NULL,
"TAGS" VARCHAR(255) DEFAULT '' NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATE_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CHECK("GROUP_ID" >= 0)
,CHECK("BATCH" >= 0)
,CHECK("TOLERANCE" >= 0)
,CHECK("TIMEOUT" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."TASK_TPL"."GROUP_ID" IS 'busi group id';
COMMENT ON COLUMN "N9E_V6"."TASK_TPL"."TAGS" IS 'split by space';

CREATE  INDEX "INDEX100023210399200" ON "N9E_V6"."TASK_TPL"("GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."TASK_TPL_HOST" cascade;
CREATE TABLE "N9E_V6"."TASK_TPL_HOST"
(
"II" BIGINT IDENTITY(1, 1) NOT NULL,
"ID" BIGINT NOT NULL,
"HOST" VARCHAR(128) NOT NULL,
NOT CLUSTER PRIMARY KEY("II"),
CHECK("ID" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."TASK_TPL_HOST"."ID" IS 'task tpl id';
COMMENT ON COLUMN "N9E_V6"."TASK_TPL_HOST"."HOST" IS 'ip or hostname';


CREATE  INDEX "INDEX100023320739600" ON "N9E_V6"."TASK_TPL_HOST"("ID" ASC,"HOST" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."TASK_RECORD" cascade;
CREATE TABLE "N9E_V6"."TASK_RECORD"
(
"ID" DECIMAL(20,0) NOT NULL,
"EVENT_ID" BIGINT DEFAULT 0 NOT NULL,
"GROUP_ID" BIGINT NOT NULL,
"IBEX_ADDRESS" VARCHAR(128) NOT NULL,
"IBEX_AUTH_USER" VARCHAR(128) DEFAULT '' NOT NULL,
"IBEX_AUTH_PASS" VARCHAR(128) DEFAULT '' NOT NULL,
"TITLE" VARCHAR(255) DEFAULT '' NOT NULL,
"ACCOUNT" VARCHAR(64) NOT NULL,
"BATCH" BIGINT DEFAULT 0 NOT NULL,
"TOLERANCE" BIGINT DEFAULT 0 NOT NULL,
"TIMEOUT" BIGINT DEFAULT 0 NOT NULL,
"PAUSE" VARCHAR(255) DEFAULT '' NOT NULL,
"SCRIPT" TEXT NOT NULL,
"ARGS" VARCHAR(512) DEFAULT '' NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CHECK("ID" >= 0)
,CHECK("BATCH" >= 0)
,CHECK("TOLERANCE" >= 0)
,CHECK("TIMEOUT" >= 0)) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."TASK_RECORD"."ID" IS 'ibex task id';
COMMENT ON COLUMN "N9E_V6"."TASK_RECORD"."EVENT_ID" IS 'event id';
COMMENT ON COLUMN "N9E_V6"."TASK_RECORD"."GROUP_ID" IS 'busi group id';


CREATE  INDEX "IDX_EVENT_ID" ON "N9E_V6"."TASK_RECORD"("EVENT_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "INDEX100023113174300" ON "N9E_V6"."TASK_RECORD"("CREATE_BY" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;
CREATE  INDEX "INDEX100023161885200" ON "N9E_V6"."TASK_RECORD"("CREATE_AT" ASC,"GROUP_ID" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."ALERTING_ENGINES" cascade;
CREATE TABLE "N9E_V6"."ALERTING_ENGINES"
(
"ID" BIGINT IDENTITY(2, 1) NOT NULL,
"INSTANCE" VARCHAR(128) DEFAULT '' NOT NULL,
"DATASOURCE_ID" BIGINT DEFAULT 0 NOT NULL,
"ENGINE_CLUSTER" VARCHAR(128) DEFAULT '' NOT NULL,
"CLOCK" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."ALERTING_ENGINES"."INSTANCE" IS 'instance identification, e.g. 10.9.0.9:9090';
COMMENT ON COLUMN "N9E_V6"."ALERTING_ENGINES"."DATASOURCE_ID" IS 'datasource id';
COMMENT ON COLUMN "N9E_V6"."ALERTING_ENGINES"."ENGINE_CLUSTER" IS 'n9e-alert cluster';

drop table if exists "N9E_V6"."DATASOURCE" cascade;
CREATE TABLE "N9E_V6"."DATASOURCE"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"NAME" VARCHAR(191) DEFAULT '' NOT NULL,
"DESCRIPTION" VARCHAR(255) DEFAULT '' NOT NULL,
"CATEGORY" VARCHAR(255) DEFAULT '' NOT NULL,
"PLUGIN_ID" INT DEFAULT 0 NOT NULL,
"PLUGIN_TYPE" VARCHAR(255) DEFAULT '' NOT NULL,
"PLUGIN_TYPE_NAME" VARCHAR(255) DEFAULT '' NOT NULL,
"CLUSTER_NAME" VARCHAR(255) DEFAULT '' NOT NULL,
"SETTINGS" TEXT NOT NULL,
"STATUS" VARCHAR(255) DEFAULT '' NOT NULL,
"HTTP" VARCHAR(4096) DEFAULT '' NOT NULL,
"AUTH" TEXT DEFAULT '' NOT NULL,
"CREATED_AT" BIGINT DEFAULT 0 NOT NULL,
"CREATED_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"UPDATED_AT" BIGINT DEFAULT 0 NOT NULL,
"UPDATED_BY" VARCHAR(64) DEFAULT '' NOT NULL,
"IS_DEFAULT" TINYINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

CREATE UNIQUE  INDEX "DATASOURCE_NAME" ON "N9E_V6"."DATASOURCE"("NAME" ASC) STORAGE(ON "N9E_V6", CLUSTERBTR) ;


drop table if exists "N9E_V6"."BUILTIN_CATE" cascade;
CREATE TABLE "N9E_V6"."BUILTIN_CATE"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"NAME" VARCHAR(191) NOT NULL,
"USER_ID" BIGINT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."NOTIFY_TPL" cascade;
CREATE TABLE "N9E_V6"."NOTIFY_TPL"
(
"ID" BIGINT IDENTITY(8, 1) NOT NULL,
"CHANNEL" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"CONTENT" TEXT NOT NULL,
"create_at" INT DEFAULT 0 ,
"create_by" VARCHAR(64) DEFAULT '' ,
"update_at" INT DEFAULT 0 ,
"update_by" VARCHAR(64) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "CHANNEL" UNIQUE("CHANNEL")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

-- SET IDENTITY_INSERT "N9E_V6"."NOTIFY_TPL" ON;
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (1, 'telegram', 'telegram', '**级别状态**: {{if .IsRecovered}}<font color=\"info\">S{{.Severity}} Recovered</font>{{else}}<font color=\"warning\">S{{.Severity}} Triggered</font>{{end}}   \n**规则标题**: {{.RuleName}}{{if .RuleNote}}   \n**规则备注**: {{.RuleNote}}{{end}}{{if .TargetIdent}}   \n**监控对象**: {{.TargetIdent}}{{end}}   \n**监控指标**: {{.TagsJSON}}{{if not .IsRecovered}}   \n**触发时值**: {{.TriggerValue}}{{end}}   \n{{if .IsRecovered}}**恢复时间**: {{timeformat .LastEvalTime}}{{else}}**首次触发时间**: {{timeformat .FirstTriggerTime}}{{end}}   \n{{$time_duration := sub now.Unix .FirstTriggerTime }}{{if .IsRecovered}}{{$time_duration = sub .LastEvalTime .FirstTriggerTime }}{{end}}**距离首次告警**: {{humanizeDurationInterface $time_duration}}\n**发送时间**: {{timestamp}}');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (2, 'wecom', 'wecom', '**级别状态**: {{if .IsRecovered}}<font color=\"info\">S{{.Severity}} Recovered</font>{{else}}<font color=\"warning\">S{{.Severity}} Triggered</font>{{end}}   \n**规则标题**: {{.RuleName}}{{if .RuleNote}}   \n**规则备注**: {{.RuleNote}}{{end}}{{if .TargetIdent}}   \n**监控对象**: {{.TargetIdent}}{{end}}   \n**监控指标**: {{.TagsJSON}}{{if not .IsRecovered}}   \n**触发时值**: {{.TriggerValue}}{{end}}   \n{{if .IsRecovered}}**恢复时间**: {{timeformat .LastEvalTime}}{{else}}**首次触发时间**: {{timeformat .FirstTriggerTime}}{{end}}   \n{{$time_duration := sub now.Unix .FirstTriggerTime }}{{if .IsRecovered}}{{$time_duration = sub .LastEvalTime .FirstTriggerTime }}{{end}}**距离首次告警**: {{humanizeDurationInterface $time_duration}}\n**发送时间**: {{timestamp}}');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (3, 'dingtalk', 'dingtalk', '#### {{if .IsRecovered}}<font color=\"#008800\">S{{.Severity}} - Recovered - {{.RuleName}}</font>{{else}}<font color=\"#FF0000\">S{{.Severity}} - Triggered - {{.RuleName}}</font>{{end}}\n\n---\n\n- **规则标题**: {{.RuleName}}{{if .RuleNote}}\n- **规则备注**: {{.RuleNote}}{{end}}\n{{if not .IsRecovered}}- **触发时值**: {{.TriggerValue}}{{end}}\n{{if .TargetIdent}}- **监控对象**: {{.TargetIdent}}{{end}}\n- **监控指标**: {{.TagsJSON}}\n- {{if .IsRecovered}}**恢复时间**: {{timeformat .LastEvalTime}}{{else}}**触发时间**: {{timeformat .TriggerTime}}{{end}}\n- **发送时间**: {{timestamp}}\n	');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (4, 'email', 'email', '<!DOCTYPE html>\n	<html lang=\"en\">\n	<head>\n		<meta charset=\"UTF-8\">\n		<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n		<title>夜莺告警通知</title>\n		<style type=\"text/css\">\n			.wrapper {\n				background-color: #f8f8f8;\n				padding: 15px;\n				height: 100%;\n			}\n			.main {\n				width: 600px;\n				padding: 30px;\n				margin: 0 auto;\n				background-color: #fff;\n				font-size: 12px;\n				font-family: verdana,Microsoft YaHei,Consolas,Deja Vu Sans Mono,Bitstream Vera Sans Mono;\n			}\n			header {\n				border-radius: 2px 2px 0 0;\n			}\n			header .title {\n				font-size: 14px;\n				color: #333333;\n				margin: 0;\n			}\n			header .sub-desc {\n				color: #333;\n				font-size: 14px;\n				margin-top: 6px;\n				margin-bottom: 0;\n			}\n			hr {\n				margin: 20px 0;\n				height: 0;\n				border: none;\n				border-top: 1px solid #e5e5e5;\n			}\n			em {\n				font-weight: 600;\n			}\n			table {\n				margin: 20px 0;\n				width: 100%;\n			}\n	\n			table tbody tr{\n				font-weight: 200;\n				font-size: 12px;\n				color: #666;\n				height: 32px;\n			}\n	\n			.succ {\n				background-color: green;\n				color: #fff;\n			}\n	\n			.fail {\n				background-color: red;\n				color: #fff;\n			}\n	\n			.succ th, .succ td, .fail th, .fail td {\n				color: #fff;\n			}\n	\n			table tbody tr th {\n				width: 80px;\n				text-align: right;\n			}\n			.text-right {\n				text-align: right;\n			}\n			.body {\n				margin-top: 24px;\n			}\n			.body-text {\n				color: #666666;\n				-webkit-font-smoothing: antialiased;\n			}\n			.body-extra {\n				-webkit-font-smoothing: antialiased;\n			}\n			.body-extra.text-right a {\n				text-decoration: none;\n				color: #333;\n			}\n			.body-extra.text-right a:hover {\n				color: #666;\n			}\n			.button {\n				width: 200px;\n				height: 50px;\n				margin-top: 20px;\n				text-align: center;\n				border-radius: 2px;\n				background: #2D77EE;\n				line-height: 50px;\n				font-size: 20px;\n				color: #FFFFFF;\n				cursor: pointer;\n			}\n			.button:hover {\n				background: rgb(25, 115, 255);\n				border-color: rgb(25, 115, 255);\n				color: #fff;\n			}\n			footer {\n				margin-top: 10px;\n				text-align: right;\n			}\n			.footer-logo {\n				text-align: right;\n			}\n			.footer-logo-image {\n				width: 108px;\n				height: 27px;\n				margin-right: 10px;\n			}\n			.copyright {\n				margin-top: 10px;\n				font-size: 12px;\n				text-align: right;\n				color: #999;\n				-webkit-font-smoothing: antialiased;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"wrapper\">\n		<div class=\"main\">\n			<header>\n				<h3 class=\"title\">{{.RuleName}}</h3>\n				<p class=\"sub-desc\"></p>\n			</header>\n	\n			<hr>\n	\n			<div class=\"body\">\n				<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n					<tbody>\n					{{if .IsRecovered}}\n					<tr class=\"succ\">\n						<th>级别状态：</th>\n						<td>S{{.Severity}} Recovered</td>\n					</tr>\n					{{else}}\n					<tr class=\"fail\">\n						<th>级别状态：</th>\n						<td>S{{.Severity}} Triggered</td>\n					</tr>\n					{{end}}\n	\n					<tr>\n						<th>策略备注：</th>\n						<td>{{.RuleNote}}</td>\n					</tr>\n					<tr>\n						<th>设备备注：</th>\n						<td>{{.TargetNote}}</td>\n					</tr>\n					{{if not .IsRecovered}}\n					<tr>\n						<th>触发时值：</th>\n						<td>{{.TriggerValue}}</td>\n					</tr>\n					{{end}}\n	\n					{{if .TargetIdent}}\n					<tr>\n						<th>监控对象：</th>\n						<td>{{.TargetIdent}}</td>\n					</tr>\n					{{end}}\n					<tr>\n						<th>监控指标：</th>\n						<td>{{.TagsJSON}}</td>\n					</tr>\n	\n					{{if .IsRecovered}}\n					<tr>\n						<th>恢复时间：</th>\n						<td>{{timeformat .LastEvalTime}}</td>\n					</tr>\n					{{else}}\n					<tr>\n						<th>触发时间：</th>\n						<td>\n							{{timeformat .TriggerTime}}\n						</td>\n					</tr>\n					{{end}}\n	\n					<tr>\n						<th>发送时间：</th>\n						<td>\n							{{timestamp}}\n						</td>\n					</tr>\n					</tbody>\n				</table>\n	\n				<hr>\n	\n				<footer>\n					<div class=\"copyright\" style=\"font-style: italic\">\n						报警太多？使用 <a href=\"https://flashcat.cloud/product/flashduty/\" target=\"_blank\">FlashDuty</a> 做告警聚合降噪、排班OnCall！\n					</div>\n				</footer>\n			</div>\n		</div>\n	</div>\n	</body>\n	</html>');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (5, 'feishu', 'feishu', '级别状态: S{{.Severity}} {{if .IsRecovered}}Recovered{{else}}Triggered{{end}}   \n规则名称: {{.RuleName}}{{if .RuleNote}}   \n规则备注: {{.RuleNote}}{{end}}   \n监控指标: {{.TagsJSON}}\n{{if .IsRecovered}}恢复时间：{{timeformat .LastEvalTime}}{{else}}触发时间: {{timeformat .TriggerTime}}\n触发时值: {{.TriggerValue}}{{end}}\n发送时间: {{timestamp}}');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (6, 'feishucard', 'feishucard', '{{ if .IsRecovered }}\n{{- if ne .Cate \"host\"}}\n**告警集群:** {{.Cluster}}{{end}}   \n**级别状态:** S{{.Severity}} Recovered   \n**告警名称:** {{.RuleName}}   \n**恢复时间:** {{timeformat .LastEvalTime}}   \n**告警描述:** **服务已恢复**   \n{{- else }}\n{{- if ne .Cate \"host\"}}   \n**告警集群:** {{.Cluster}}{{end}}   \n**级别状态:** S{{.Severity}} Triggered   \n**告警名称:** {{.RuleName}}   \n**触发时间:** {{timeformat .TriggerTime}}   \n**发送时间:** {{timestamp}}   \n**触发时值:** {{.TriggerValue}}   \n{{if .RuleNote }}**告警描述:** **{{.RuleNote}}**{{end}}   \n{{- end -}}');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (7, 'mailsubject', 'mailsubject', '{{if .IsRecovered}}Recovered{{else}}Triggered{{end}}: {{.RuleName}} {{.TagsJSON}}');
-- INSERT INTO "N9E_V6"."NOTIFY_TPL"(id,channel,name,content) VALUES (8, 'mm', 'mm', '级别状态: S{{.Severity}} {{if .IsRecovered}}Recovered{{else}}Triggered{{end}}   \n规则名称: {{.RuleName}}{{if .RuleNote}}   \n规则备注: {{.RuleNote}}{{end}}   \n监控指标: {{.TagsJSON}}   \n{{if .IsRecovered}}恢复时间：{{timeformat .LastEvalTime}}{{else}}触发时间: {{timeformat .TriggerTime}}   \n触发时值: {{.TriggerValue}}{{end}}   \n发送时间: {{timestamp}}');

drop table if exists "N9E_V6"."SSO_CONFIG" cascade;
CREATE TABLE "N9E_V6"."SSO_CONFIG"
(
"ID" BIGINT IDENTITY(4, 1) NOT NULL,
"NAME" VARCHAR(191) NOT NULL,
"CONTENT" TEXT NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("NAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

drop table if exists "N9E_V6"."ES_INDEX_PATTERN" cascade;
CREATE TABLE "N9E_V6"."ES_INDEX_PATTERN"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"DATASOURCE_ID" BIGINT DEFAULT 0 NOT NULL,
"NAME" VARCHAR(191) NOT NULL,
"TIME_FIELD" VARCHAR(128) DEFAULT '@timestamp' NOT NULL,
"ALLOW_HIDE_SYSTEM_INDICES" TINYINT DEFAULT 0 NOT NULL,
"FIELDS_FORMAT" VARCHAR(4096) DEFAULT '' NOT NULL,
"CREATE_AT" BIGINT DEFAULT 0,
"CREATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_AT" BIGINT DEFAULT 0,
"UPDATE_BY" VARCHAR(64) DEFAULT '',
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "DATASOURCE_ID" UNIQUE("DATASOURCE_ID", "NAME")) STORAGE(ON "N9E_V6", CLUSTERBTR) ;

COMMENT ON COLUMN "N9E_V6"."ES_INDEX_PATTERN"."DATASOURCE_ID" IS 'datasource id';